
import twitter4j.User;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author BuckYoung
 */
public class FoundUser extends javax.swing.JPanel {

    User user;

    /**
     * Creates new form FoundUser
     */
    public FoundUser(User user) {
        initComponents();
        pic.setIcon(UserIconLogic.getIcon(user, UserIconLogic.Size.MINI)); //get Mini!
        userName.setText("@" + user.getScreenName());
        location.setText(user.getLocation());
        try {
            description.setText(user.getDescription().substring(0, 40) + "...");
        } catch (NullPointerException npe) {
            description.setText(null);
        } catch (IndexOutOfBoundsException iobe) {
            description.setText(null);
        }
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pic = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        location = new javax.swing.JLabel();
        description = new javax.swing.JLabel();

        setBackground(new java.awt.Color(200, 240, 250));
        setPreferredSize(new java.awt.Dimension(350, 100));

        pic.setBackground(new java.awt.Color(200, 240, 250));
        pic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pic.setPreferredSize(new java.awt.Dimension(24, 24));
        pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                picMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                picMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                picMouseEntered(evt);
            }
        });

        userName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        userName.setText("UserName");

        location.setText("location");

        description.setText("Description");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(pic, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(userName))
                    .add(description)
                    .add(location))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pic, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, userName))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(location)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(description)
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /*
     * creates timeline when pic is clicked
     */
    private void picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_picMouseClicked
      Timeline.createTimeline(Timeline.Type.USER, user, null); //load their timeline
    }//GEN-LAST:event_picMouseClicked

    /*
     * Border creation for mouseOvers:
     */
    private void picMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_picMouseEntered
      pic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    }//GEN-LAST:event_picMouseEntered

    private void picMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_picMouseExited
      pic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_picMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel description;
    private javax.swing.JLabel location;
    private javax.swing.JLabel pic;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables

}
