
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import twitter4j.Relationship;
import twitter4j.TwitterException;
import twitter4j.User;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author BuckYoung
 */
public class UserPanel extends javax.swing.JPanel {
    
    
    private boolean wasFollowing;
    private User user;
    /**
     * Creates new form UserPanel
     */
    public UserPanel(User user) {
         Twitty401.mainGUI.setAllUnselected();
         
        this.user = user;

        initComponents();
        realName.setText(user.getName());
        userName.setText("@"+user.getScreenName());
        bigPic.setIcon(UserIconLogic.getIcon(user,UserIconLogic.Size.BIG));
        followerCount.setText(user.getFollowersCount() + " followers");
        location.setText(user.getLocation());
        
        //Compares authenticating user with UserPanel user -- friends?
        Relationship rl;
        try {
            rl = Twitty401.twitter.showFriendship(Twitty401.twitter.getScreenName(), user.getScreenName());
            if (rl.isSourceFollowingTarget()) {
                followingCheck.setSelected(true);
                wasFollowing = true;
            } else {
                followingCheck.setSelected(false);
                wasFollowing = false;
            }
        } catch (TwitterException ex) {
            Logger.getLogger(UserPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalStateException ex) {
            Logger.getLogger(UserPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userName = new javax.swing.JLabel();
        bigPic = new javax.swing.JLabel();
        followingCheck = new javax.swing.JCheckBox();
        realName = new javax.swing.JLabel();
        location = new javax.swing.JLabel();
        followerCount = new javax.swing.JLabel();

        setBackground(new java.awt.Color(160, 200, 240));
        setBounds(new java.awt.Rectangle(0, 0, 350, 150));
        setMaximumSize(new java.awt.Dimension(350, 150));
        setMinimumSize(new java.awt.Dimension(350, 130));
        setPreferredSize(new java.awt.Dimension(350, 118));

        jPanel1.setBackground(new java.awt.Color(200, 240, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(330, 118));

        userName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        userName.setText("@theeprofessir");

        bigPic.setToolTipText("");
        bigPic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bigPic.setPreferredSize(new java.awt.Dimension(73, 73));
        bigPic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bigPicMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bigPicMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bigPicMouseEntered(evt);
            }
        });

        followingCheck.setText("Following");
        followingCheck.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        followingCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followingCheckActionPerformed(evt);
            }
        });

        realName.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        realName.setText("Buck Young");

        location.setText("Location");

        followerCount.setText("Followers: ");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(bigPic, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(realName)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(6, 6, 6)
                                .add(userName))
                            .add(location))
                        .add(0, 83, Short.MAX_VALUE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(followingCheck)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(followerCount)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(6, 6, 6)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(bigPic, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(realName)
                        .add(6, 6, 6)
                        .add(userName)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(location)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(followingCheck)
                    .add(followerCount))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 331, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void followingCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followingCheckActionPerformed
        //CREATES AND DESTROYS FRIENDSHIPS
        if (wasFollowing){
            try {
                Twitty401.twitter.destroyFriendship(user.getId());
                
            } catch (TwitterException ex) {
                Logger.getLogger(UserPanel.class.getName()).log(Level.SEVERE, null, ex);
                //if fail, keep checked
                followingCheck.setSelected(true);
            }
        } else {
            try {
                Twitty401.twitter.createFriendship(user.getId());
            } catch (TwitterException ex) {
                Logger.getLogger(UserPanel.class.getName()).log(Level.SEVERE, null, ex);
                //if fail, keep unchecked
                followingCheck.setSelected(false);
            }
        }
        wasFollowing = !wasFollowing;
    }//GEN-LAST:event_followingCheckActionPerformed

    private void bigPicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bigPicMouseClicked
          Timeline.createTimeline(Timeline.Type.USER, user, null); //reload their timeline
          PopUp.destroyPopup();
    }//GEN-LAST:event_bigPicMouseClicked

    private void bigPicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bigPicMouseEntered
      bigPic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    }//GEN-LAST:event_bigPicMouseEntered

    private void bigPicMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bigPicMouseExited
      bigPic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_bigPicMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bigPic;
    private javax.swing.JLabel followerCount;
    private javax.swing.JCheckBox followingCheck;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel location;
    private javax.swing.JLabel realName;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables

    /*
     *  add a userpanel when "visiting"
     */
    public static void addUserPanel(User user) {
        UserPanel upanel = new UserPanel(user);
        MainGUI.addToMainPanel(upanel);
    }
}
